// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. Operation Codes (What is happening?)
type OpCode int32

const (
	OpCode_OP_UNKNOWN             OpCode = 0
	OpCode_OP_MATCH_START         OpCode = 1 // Server -> Client (Deal cards)
	OpCode_OP_PLAY_CARD           OpCode = 2 // Client -> Server (Player move)
	OpCode_OP_TURN_UPDATE         OpCode = 3 // Server -> Client (Next player turn)
	OpCode_OP_ERROR               OpCode = 4 // Server -> Client (Invalid move)
	OpCode_OP_MATCH_START_REQUEST OpCode = 5 // Client -> Server (Host initiates game start)
	OpCode_OP_OWNER_UPDATE        OpCode = 6 // Server -> Client (Notify new owner)
	OpCode_OP_GAME_OVER           OpCode = 7 // Server -> Client (Round finished)
	OpCode_OP_MATCH_STATE         OpCode = 8 // Server -> Client (Sync state for late joiner)
	OpCode_OP_HAND_UPDATE         OpCode = 9 // Server -> Client (Update player's hand)
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OP_UNKNOWN",
		1: "OP_MATCH_START",
		2: "OP_PLAY_CARD",
		3: "OP_TURN_UPDATE",
		4: "OP_ERROR",
		5: "OP_MATCH_START_REQUEST",
		6: "OP_OWNER_UPDATE",
		7: "OP_GAME_OVER",
		8: "OP_MATCH_STATE",
		9: "OP_HAND_UPDATE",
	}
	OpCode_value = map[string]int32{
		"OP_UNKNOWN":             0,
		"OP_MATCH_START":         1,
		"OP_PLAY_CARD":           2,
		"OP_TURN_UPDATE":         3,
		"OP_ERROR":               4,
		"OP_MATCH_START_REQUEST": 5,
		"OP_OWNER_UPDATE":        6,
		"OP_GAME_OVER":           7,
		"OP_MATCH_STATE":         8,
		"OP_HAND_UPDATE":         9,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

// 2. Data Structures
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          int32                  `protobuf:"varint,1,opt,name=suit,proto3" json:"suit,omitempty"` // 0=Spade, 1=Club, 2=Diamond, 3=Heart
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"` // 3=0... 2=12
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetSuit() int32 {
	if x != nil {
		return x.Suit
	}
	return 0
}

func (x *Card) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type HandUpdatePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hand          []*Card                `protobuf:"bytes,1,rep,name=hand,proto3" json:"hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandUpdatePacket) Reset() {
	*x = HandUpdatePacket{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandUpdatePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandUpdatePacket) ProtoMessage() {}

func (x *HandUpdatePacket) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandUpdatePacket.ProtoReflect.Descriptor instead.
func (*HandUpdatePacket) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *HandUpdatePacket) GetHand() []*Card {
	if x != nil {
		return x.Hand
	}
	return nil
}

type MatchStartPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hand          []*Card                `protobuf:"bytes,1,rep,name=hand,proto3" json:"hand,omitempty"`                            // Your cards
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // Turn order
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`       // The ID of the current match owner
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartPacket) Reset() {
	*x = MatchStartPacket{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartPacket) ProtoMessage() {}

func (x *MatchStartPacket) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartPacket.ProtoReflect.Descriptor instead.
func (*MatchStartPacket) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *MatchStartPacket) GetHand() []*Card {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *MatchStartPacket) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchStartPacket) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GameOverPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerId      string                 `protobuf:"bytes,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOverPacket) Reset() {
	*x = GameOverPacket{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOverPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverPacket) ProtoMessage() {}

func (x *GameOverPacket) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverPacket.ProtoReflect.Descriptor instead.
func (*GameOverPacket) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameOverPacket) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

type MatchStatePacket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsPlaying      bool                   `protobuf:"varint,1,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	OwnerId        string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Board          []*Card                `protobuf:"bytes,3,rep,name=board,proto3" json:"board,omitempty"`
	ActivePlayerId string                 `protobuf:"bytes,4,opt,name=active_player_id,json=activePlayerId,proto3" json:"active_player_id,omitempty"`
	PlayerIds      []string               `protobuf:"bytes,5,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // Who is currently playing
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchStatePacket) Reset() {
	*x = MatchStatePacket{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatePacket) ProtoMessage() {}

func (x *MatchStatePacket) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatePacket.ProtoReflect.Descriptor instead.
func (*MatchStatePacket) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *MatchStatePacket) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *MatchStatePacket) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MatchStatePacket) GetBoard() []*Card {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *MatchStatePacket) GetActivePlayerId() string {
	if x != nil {
		return x.ActivePlayerId
	}
	return ""
}

func (x *MatchStatePacket) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type PlayCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardIndices   []int32                `protobuf:"varint,1,rep,packed,name=card_indices,json=cardIndices,proto3" json:"card_indices,omitempty"` // Indices of cards in hand to play
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayCardRequest) Reset() {
	*x = PlayCardRequest{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCardRequest) ProtoMessage() {}

func (x *PlayCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCardRequest.ProtoReflect.Descriptor instead.
func (*PlayCardRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *PlayCardRequest) GetCardIndices() []int32 {
	if x != nil {
		return x.CardIndices
	}
	return nil
}

type TurnUpdatePacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActivePlayerId   string                 `protobuf:"bytes,1,opt,name=active_player_id,json=activePlayerId,proto3" json:"active_player_id,omitempty"`
	LastPlayedCards  []*Card                `protobuf:"bytes,2,rep,name=last_played_cards,json=lastPlayedCards,proto3" json:"last_played_cards,omitempty"` // Cards currently on table
	SecondsRemaining int32                  `protobuf:"varint,3,opt,name=seconds_remaining,json=secondsRemaining,proto3" json:"seconds_remaining,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TurnUpdatePacket) Reset() {
	*x = TurnUpdatePacket{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnUpdatePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnUpdatePacket) ProtoMessage() {}

func (x *TurnUpdatePacket) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnUpdatePacket.ProtoReflect.Descriptor instead.
func (*TurnUpdatePacket) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *TurnUpdatePacket) GetActivePlayerId() string {
	if x != nil {
		return x.ActivePlayerId
	}
	return ""
}

func (x *TurnUpdatePacket) GetLastPlayedCards() []*Card {
	if x != nil {
		return x.LastPlayedCards
	}
	return nil
}

func (x *TurnUpdatePacket) GetSecondsRemaining() int32 {
	if x != nil {
		return x.SecondsRemaining
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x03api\".\n" +
	"\x04Card\x12\x12\n" +
	"\x04suit\x18\x01 \x01(\x05R\x04suit\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\"1\n" +
	"\x10HandUpdatePacket\x12\x1d\n" +
	"\x04hand\x18\x01 \x03(\v2\t.api.CardR\x04hand\"k\n" +
	"\x10MatchStartPacket\x12\x1d\n" +
	"\x04hand\x18\x01 \x03(\v2\t.api.CardR\x04hand\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\"-\n" +
	"\x0eGameOverPacket\x12\x1b\n" +
	"\twinner_id\x18\x01 \x01(\tR\bwinnerId\"\xb6\x01\n" +
	"\x10MatchStatePacket\x12\x1d\n" +
	"\n" +
	"is_playing\x18\x01 \x01(\bR\tisPlaying\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1f\n" +
	"\x05board\x18\x03 \x03(\v2\t.api.CardR\x05board\x12(\n" +
	"\x10active_player_id\x18\x04 \x01(\tR\x0eactivePlayerId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x05 \x03(\tR\tplayerIds\"4\n" +
	"\x0fPlayCardRequest\x12!\n" +
	"\fcard_indices\x18\x01 \x03(\x05R\vcardIndices\"\xa0\x01\n" +
	"\x10TurnUpdatePacket\x12(\n" +
	"\x10active_player_id\x18\x01 \x01(\tR\x0eactivePlayerId\x125\n" +
	"\x11last_played_cards\x18\x02 \x03(\v2\t.api.CardR\x0flastPlayedCards\x12+\n" +
	"\x11seconds_remaining\x18\x03 \x01(\x05R\x10secondsRemaining*\xcb\x01\n" +
	"\x06OpCode\x12\x0e\n" +
	"\n" +
	"OP_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eOP_MATCH_START\x10\x01\x12\x10\n" +
	"\fOP_PLAY_CARD\x10\x02\x12\x12\n" +
	"\x0eOP_TURN_UPDATE\x10\x03\x12\f\n" +
	"\bOP_ERROR\x10\x04\x12\x1a\n" +
	"\x16OP_MATCH_START_REQUEST\x10\x05\x12\x13\n" +
	"\x0fOP_OWNER_UPDATE\x10\x06\x12\x10\n" +
	"\fOP_GAME_OVER\x10\a\x12\x12\n" +
	"\x0eOP_MATCH_STATE\x10\b\x12\x12\n" +
	"\x0eOP_HAND_UPDATE\x10\tB\x14Z\x04./pb\xaa\x02\vTienLen.Genb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_game_proto_goTypes = []any{
	(OpCode)(0),              // 0: api.OpCode
	(*Card)(nil),             // 1: api.Card
	(*HandUpdatePacket)(nil), // 2: api.HandUpdatePacket
	(*MatchStartPacket)(nil), // 3: api.MatchStartPacket
	(*GameOverPacket)(nil),   // 4: api.GameOverPacket
	(*MatchStatePacket)(nil), // 5: api.MatchStatePacket
	(*PlayCardRequest)(nil),  // 6: api.PlayCardRequest
	(*TurnUpdatePacket)(nil), // 7: api.TurnUpdatePacket
}
var file_game_proto_depIdxs = []int32{
	1, // 0: api.HandUpdatePacket.hand:type_name -> api.Card
	1, // 1: api.MatchStartPacket.hand:type_name -> api.Card
	1, // 2: api.MatchStatePacket.board:type_name -> api.Card
	1, // 3: api.TurnUpdatePacket.last_played_cards:type_name -> api.Card
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
